version: '3.8'
services:
  server:
    image: postgrest/postgrest
    ports:
      - "3001:3000"
    environment:
      PGRST_DB_URI: postgres://root:123456@db:5432/app_db
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: webuser
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3001
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./conf/init.sql:/docker-entrypoint-initdb.d/init.sql  # 挂载初始化SQL脚本
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    environment:
      API_URL: http://127.0.0.1:3001
volumes:
  postgres_data:
    driver: local                                  # 持久化卷，使用本地存储