version: '3'
services:
  docker-fe-01:
    image: "apache/doris:2.0.0_alpha-fe-x86_64"
    container_name: "doris-fe-01"
    hostname: "fe-01"
    environment:
      - FE_SERVERS=fe1:172.22.80.10:9010
      - FE_ID=1
    ports:
      - "8030:8030"
      - "9030:9030"
    volumes:
      - /usr/local/docker-data/doris/fe-01/doris-meta:/opt/apache-doris/fe/doris-meta
      - /usr/local/docker-data/doris/fe-01/log:/opt/apache-doris/fe/log
    networks:
      doris_net:
        ipv4_address: 172.22.80.10
  docker-be-01:
    image: "apache/doris:2.0.0_alpha-be-x86_64"
    container_name: "doris-be-01"
    hostname: "be-01"
    depends_on:
      - docker-fe-01
    environment:
      - FE_SERVERS=fe1:172.22.80.10:9010
      - BE_ADDR=172.22.80.20:9050
    ports:
      - "8040:8040"
    volumes:
      - /usr/local/docker-data/doris/be-01/storage:/opt/apache-doris/be/storage
      - /usr/local/docker-data/doris/be-01/script:/docker-entrypoint-initdb.d
      - /usr/local/docker-data/doris/be-01/log:/opt/apache-doris/be/log
    networks:
      doris_net:
        ipv4_address: 172.22.80.20
networks:
  doris_net:
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - subnet: 172.22.80.0/24
          gateway: 172.22.80.1