# clash官方配置文档：https://dreamacro.github.io/clash/
mixed-port: 7890
# RESTful API for clash
external-controller: 127.0.0.1:9090
allow-lan: false
mode: rule
log-level: warning

proxies:
  - name: TEST_TROJAN
    type: trojan
    server: test.example.com # 你自己的服务器域名
    port: 6443 # 注意端口
    password: 123456 # trojan配置文件中的密码
    udp: true
    sni: test.example.com # 你自己的服务器域名

proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - TEST_TROJAN
  - name: Final
    type: select
    proxies:
      - DIRECT
      - PROXY
rules:
  # Local Area Network
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  # DNSPod Public DNS+
  - IP-CIDR,119.28.28.28/32,DIRECT,no-resolve
  # GeoIP China
  - GEOIP,CN,DIRECT

  - MATCH,Final