version: '3'
services:
  trojan-go:
    image: p4gefau1t/trojan-go
    restart: always
    networks:
      - trojan-go-network
    depends_on:
      - nginx-service
    ports:
      - "6443:443"
    volumes:
      - ./config/trojan-go-server.json:/etc/trojan-go/config.json
      - ./config/fullchain.pem:/etc/trojan-go/fullchain.pem
      - ./config/privkey.pem:/etc/trojan-go/privkey.pem
#      - /etc/letsencrypt/live/test.example.org/fullchain.pem:/etc/trojan-go/fullchain.pem
#      - /etc/letsencrypt/live/test.example.org/privkey.pem:/etc/trojan-go/privkey.pem
  nginx-service:
    image: nginx:1.19.0-alpine
    restart: always
    networks:
      - trojan-go-network
networks:
  trojan-go-network:
    driver: bridge