ARG IMAGE_BASE="nginx"
ARG IMAGE_TAG="1.21.6"

FROM ${IMAGE_BASE}:${IMAGE_TAG}

ARG IMAGE_BASE="nginx"
ARG IMAGE_TAG="1.21.6"

RUN echo '<h2>Hello, Docker! -- '${IMAGE_BASE}${IMAGE_TAG}'</h2>' > /usr/share/nginx/html/index.html