version: "3.8"
services:
  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    env_file:
      - ./env/nacos-standalone-mysql.env
    volumes:
      - nacos_data:/home/nacos/data
    ports:
      - "28080:8080"
      - "8848:8848"
      - "9848:9848"
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: bitnami/mysql:latest
    env_file:
      - ./env/mysql.env
    volumes:
      - mysql_data:/bitnami/mysql                  # 数据持久化卷
      - ./conf/nacos-mysql-init.sql:/docker-entrypoint-initdb.d/nacos-mysql-init.sql
    ports:
      - "13306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  mysql_data:
    driver: local                                  # 持久化卷，使用本地存储
  nacos_data:
    driver: local


