ARG IMAGE_BASE="openresty/openresty"
ARG IMAGE_TAG="1.21.4.1rc3-1-centos7"

FROM ${IMAGE_BASE}:${IMAGE_TAG}

ARG IMAGE_BASE="openresty/openresty"
ARG IMAGE_TAG="1.21.4.1rc3-1-centos7"

RUN echo '<h2>Hello, Docker! -- '${IMAGE_BASE}${IMAGE_TAG}'</h2>' > /usr/local/openresty/nginx/html/index.html